// Code generated by htmlgen; DO NOT EDIT.
package html

type AProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func A(p AProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "a", props: a, void: false, children: children}
}
