// Code generated by htmlgen; DO NOT EDIT.
package html

type AbbrProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Abbr(p AbbrProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "abbr", props: a, void: false, children: children}
}
