// Code generated by htmlgen; DO NOT EDIT.
package html

type AcceptsCssColorsProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func AcceptsCssColors(p AcceptsCssColorsProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "accepts_css_colors", props: a, void: false, children: children}
}
