// Code generated by htmlgen; DO NOT EDIT.
package html

type AcceptProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Accept(p AcceptProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "accept", props: a, void: false, children: children}
}
