// Code generated by htmlgen; DO NOT EDIT.
package html

type AcceptCharsetProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func AcceptCharset(p AcceptCharsetProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "accept-charset", props: a, void: false, children: children}
}
