// Code generated by htmlgen; DO NOT EDIT.
package html

type ActionProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Action(p ActionProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "action", props: a, void: false, children: children}
}
