// Code generated by htmlgen; DO NOT EDIT.
package html

type AlignProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Align(p AlignProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "align", props: a, void: false, children: children}
}
