// Code generated by htmlgen; DO NOT EDIT.
package html

type AlinkProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Alink(p AlinkProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "alink", props: a, void: false, children: children}
}
