// Code generated by htmlgen; DO NOT EDIT.
package html

type AllowTopNavigationByUserActivationProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func AllowTopNavigationByUserActivation(p AllowTopNavigationByUserActivationProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "allow-top-navigation-by-user-activation", props: a, void: false, children: children}
}
