// Code generated by htmlgen; DO NOT EDIT.
package html

type AllowPopupsProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func AllowPopups(p AllowPopupsProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "allow-popups", props: a, void: false, children: children}
}
