// Code generated by htmlgen; DO NOT EDIT.
package html

type AllowStorageAccessByUserActivationProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func AllowStorageAccessByUserActivation(p AllowStorageAccessByUserActivationProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "allow-storage-access-by-user-activation", props: a, void: false, children: children}
}
