// Code generated by htmlgen; DO NOT EDIT.
package html

type AllowScriptsProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func AllowScripts(p AllowScriptsProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "allow-scripts", props: a, void: false, children: children}
}
