// Code generated by htmlgen; DO NOT EDIT.
package html

type AllowTopNavigationToCustomProtocolsProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func AllowTopNavigationToCustomProtocols(p AllowTopNavigationToCustomProtocolsProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "allow-top-navigation-to-custom-protocols", props: a, void: false, children: children}
}
