// Code generated by htmlgen; DO NOT EDIT.
package html

type AllowPresentationProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func AllowPresentation(p AllowPresentationProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "allow-presentation", props: a, void: false, children: children}
}
