// Code generated by htmlgen; DO NOT EDIT.
package html

type AllowfullscreenProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Allowfullscreen(p AllowfullscreenProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "allowfullscreen", props: a, void: false, children: children}
}
