// Code generated by htmlgen; DO NOT EDIT.
package html

type AllowPointerLockProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func AllowPointerLock(p AllowPointerLockProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "allow-pointer-lock", props: a, void: false, children: children}
}
