// Code generated by htmlgen; DO NOT EDIT.
package html

type AllowFormsProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func AllowForms(p AllowFormsProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "allow-forms", props: a, void: false, children: children}
}
