// Code generated by htmlgen; DO NOT EDIT.
package html

type AllowSameOriginProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func AllowSameOrigin(p AllowSameOriginProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "allow-same-origin", props: a, void: false, children: children}
}
