// Code generated by htmlgen; DO NOT EDIT.
package html

type AllowDownloadsProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func AllowDownloads(p AllowDownloadsProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "allow-downloads", props: a, void: false, children: children}
}
