// Code generated by htmlgen; DO NOT EDIT.
package html

type AllowTopNavigationProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func AllowTopNavigation(p AllowTopNavigationProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "allow-top-navigation", props: a, void: false, children: children}
}
