// Code generated by htmlgen; DO NOT EDIT.
package html

type AllowPopupsToEscapeSandboxProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func AllowPopupsToEscapeSandbox(p AllowPopupsToEscapeSandboxProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "allow-popups-to-escape-sandbox", props: a, void: false, children: children}
}
