// Code generated by htmlgen; DO NOT EDIT.
package html

type AllowpaymentrequestProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Allowpaymentrequest(p AllowpaymentrequestProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "allowpaymentrequest", props: a, void: false, children: children}
}
