// Code generated by htmlgen; DO NOT EDIT.
package html

type AlphaProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Alpha(p AlphaProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "alpha", props: a, void: false, children: children}
}
