// Code generated by htmlgen; DO NOT EDIT.
package html

type AltProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Alt(p AltProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "alt", props: a, void: false, children: children}
}
