// Code generated by htmlgen; DO NOT EDIT.
package html

type AmbientLightSensorProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func AmbientLightSensor(p AmbientLightSensorProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "ambient-light-sensor", props: a, void: false, children: children}
}
