// Code generated by htmlgen; DO NOT EDIT.
package html

type AnonymousClientIpWhenCrossOriginProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func AnonymousClientIpWhenCrossOrigin(p AnonymousClientIpWhenCrossOriginProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "anonymous-client-ip-when-cross-origin", props: a, void: false, children: children}
}
