// Code generated by htmlgen; DO NOT EDIT.
package html

type ArchiveProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Archive(p ArchiveProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "archive", props: a, void: false, children: children}
}
