// Code generated by htmlgen; DO NOT EDIT.
package html

type ArticleProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Article(p ArticleProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "article", props: a, void: false, children: children}
}
