// Code generated by htmlgen; DO NOT EDIT.
package html

type AsFontProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func AsFont(p AsFontProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "as-font", props: a, void: false, children: children}
}
