// Code generated by htmlgen; DO NOT EDIT.
package html

type AsFetchProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func AsFetch(p AsFetchProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "as-fetch", props: a, void: false, children: children}
}
