// Code generated by htmlgen; DO NOT EDIT.
package html

type AsImageProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func AsImage(p AsImageProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "as-image", props: a, void: false, children: children}
}
