// Code generated by htmlgen; DO NOT EDIT.
package html

type AsJsonProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func AsJson(p AsJsonProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "as-json", props: a, void: false, children: children}
}
