// Code generated by htmlgen; DO NOT EDIT.
package html

type AsScriptProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func AsScript(p AsScriptProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "as-script", props: a, void: false, children: children}
}
