// Code generated by htmlgen; DO NOT EDIT.
package html

type AsStyleProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func AsStyle(p AsStyleProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "as-style", props: a, void: false, children: children}
}
