// Code generated by htmlgen; DO NOT EDIT.
package html

type AsTrackProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func AsTrack(p AsTrackProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "as-track", props: a, void: false, children: children}
}
