// Code generated by htmlgen; DO NOT EDIT.
package html

type AsProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func As(p AsProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "as", props: a, void: false, children: children}
}
