// Code generated by htmlgen; DO NOT EDIT.
package html

type AsideProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Aside(p AsideProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "aside", props: a, void: false, children: children}
}
