// Code generated by htmlgen; DO NOT EDIT.
package html

type AspectRatioComputedFromAttributesProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func AspectRatioComputedFromAttributes(p AspectRatioComputedFromAttributesProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "aspect_ratio_computed_from_attributes", props: a, void: false, children: children}
}
