// Code generated by htmlgen; DO NOT EDIT.
package html

type AsyncProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Async(p AsyncProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "async", props: a, void: false, children: children}
}
