// Code generated by htmlgen; DO NOT EDIT.
package html

type AttributionsrcProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Attributionsrc(p AttributionsrcProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "attributionsrc", props: a, void: false, children: children}
}
