// Code generated by htmlgen; DO NOT EDIT.
package html

type AttributionReportingProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func AttributionReporting(p AttributionReportingProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "attribution-reporting", props: a, void: false, children: children}
}
