// Code generated by htmlgen; DO NOT EDIT.
package html

type AutoplayProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Autoplay(p AutoplayProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "autoplay", props: a, void: false, children: children}
}
