// Code generated by htmlgen; DO NOT EDIT.
package html

type AutolocateProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Autolocate(p AutolocateProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "autolocate", props: a, void: false, children: children}
}
