// Code generated by htmlgen; DO NOT EDIT.
package html

type AutoProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Auto(p AutoProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "auto", props: a, void: false, children: children}
}
