// Code generated by htmlgen; DO NOT EDIT.
package html

type AxisProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Axis(p AxisProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "axis", props: a, void: false, children: children}
}
