// Code generated by htmlgen; DO NOT EDIT.
package html

type BProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func B(p BProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "b", props: a, void: false, children: children}
}
