// Code generated by htmlgen; DO NOT EDIT.
package html

type BackgroundProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Background(p BackgroundProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "background", props: a, void: false, children: children}
}
