// Code generated by htmlgen; DO NOT EDIT.
package html

type BaseProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Base(p BaseProps) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "base", props: a, void: true}
}
