// Code generated by htmlgen; DO NOT EDIT.
package html

type BdoProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Bdo(p BdoProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "bdo", props: a, void: false, children: children}
}
