// Code generated by htmlgen; DO NOT EDIT.
package html

type BehaviorProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Behavior(p BehaviorProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "behavior", props: a, void: false, children: children}
}
