// Code generated by htmlgen; DO NOT EDIT.
package html

type BgcolorProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Bgcolor(p BgcolorProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "bgcolor", props: a, void: false, children: children}
}
