// Code generated by htmlgen; DO NOT EDIT.
package html

type BigProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Big(p BigProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "big", props: a, void: false, children: children}
}
