// Code generated by htmlgen; DO NOT EDIT.
package html

type BlockingProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Blocking(p BlockingProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "blocking", props: a, void: false, children: children}
}
