// Code generated by htmlgen; DO NOT EDIT.
package html

type BluetoothProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Bluetooth(p BluetoothProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "bluetooth", props: a, void: false, children: children}
}
