// Code generated by htmlgen; DO NOT EDIT.
package html

type BodyProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Body(p BodyProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "body", props: a, void: false, children: children}
}
