// Code generated by htmlgen; DO NOT EDIT.
package html

type BottommarginProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Bottommargin(p BottommarginProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "bottommargin", props: a, void: false, children: children}
}
