// Code generated by htmlgen; DO NOT EDIT.
package html

type BrowsingTopicsProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func BrowsingTopics(p BrowsingTopicsProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "browsing-topics", props: a, void: false, children: children}
}
