// Code generated by htmlgen; DO NOT EDIT.
package html

type BrowsingtopicsProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Browsingtopics(p BrowsingtopicsProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "browsingtopics", props: a, void: false, children: children}
}
