// Code generated by htmlgen; DO NOT EDIT.
package html

type CameraProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Camera(p CameraProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "camera", props: a, void: false, children: children}
}
