// Code generated by htmlgen; DO NOT EDIT.
package html

type CanvasProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Canvas(p CanvasProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "canvas", props: a, void: false, children: children}
}
