// Code generated by htmlgen; DO NOT EDIT.
package html

type CaptionProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Caption(p CaptionProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "caption", props: a, void: false, children: children}
}
