// Code generated by htmlgen; DO NOT EDIT.
package html

type CellpaddingProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Cellpadding(p CellpaddingProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "cellpadding", props: a, void: false, children: children}
}
