// Code generated by htmlgen; DO NOT EDIT.
package html

type CellspacingProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Cellspacing(p CellspacingProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "cellspacing", props: a, void: false, children: children}
}
