// Code generated by htmlgen; DO NOT EDIT.
package html

type CenterProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Center(p CenterProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "center", props: a, void: false, children: children}
}
