// Code generated by htmlgen; DO NOT EDIT.
package html

type CharsetProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Charset(p CharsetProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "charset", props: a, void: false, children: children}
}
