// Code generated by htmlgen; DO NOT EDIT.
package html

type CharoffProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Charoff(p CharoffProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "charoff", props: a, void: false, children: children}
}
