// Code generated by htmlgen; DO NOT EDIT.
package html

type CharProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Char(p CharProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "char", props: a, void: false, children: children}
}
