// Code generated by htmlgen; DO NOT EDIT.
package html

type ClassidProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Classid(p ClassidProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "classid", props: a, void: false, children: children}
}
