// Code generated by htmlgen; DO NOT EDIT.
package html

type ClearProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Clear(p ClearProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "clear", props: a, void: false, children: children}
}
