// Code generated by htmlgen; DO NOT EDIT.
package html

type ClosedbyProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Closedby(p ClosedbyProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "closedby", props: a, void: false, children: children}
}
