// Code generated by htmlgen; DO NOT EDIT.
package html

type CodetypeProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Codetype(p CodetypeProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "codetype", props: a, void: false, children: children}
}
