// Code generated by htmlgen; DO NOT EDIT.
package html

type ColorSchemeProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func ColorScheme(p ColorSchemeProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "color-scheme", props: a, void: false, children: children}
}
