// Code generated by htmlgen; DO NOT EDIT.
package html

type ColorspaceProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Colorspace(p ColorspaceProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "colorspace", props: a, void: false, children: children}
}
