// Code generated by htmlgen; DO NOT EDIT.
package html

type ColorProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Color(p ColorProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "color", props: a, void: false, children: children}
}
