// Code generated by htmlgen; DO NOT EDIT.
package html

type ColspanProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Colspan(p ColspanProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "colspan", props: a, void: false, children: children}
}
