// Code generated by htmlgen; DO NOT EDIT.
package html

type ColsProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Cols(p ColsProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "cols", props: a, void: false, children: children}
}
