// Code generated by htmlgen; DO NOT EDIT.
package html

type CommandforProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Commandfor(p CommandforProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "commandfor", props: a, void: false, children: children}
}
