// Code generated by htmlgen; DO NOT EDIT.
package html

type CompressionDictionaryProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func CompressionDictionary(p CompressionDictionaryProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "compression-dictionary", props: a, void: false, children: children}
}
