// Code generated by htmlgen; DO NOT EDIT.
package html

type CompactProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Compact(p CompactProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "compact", props: a, void: false, children: children}
}
