// Code generated by htmlgen; DO NOT EDIT.
package html

type ContentProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Content(p ContentProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "content", props: a, void: false, children: children}
}
