// Code generated by htmlgen; DO NOT EDIT.
package html

type ContentTypeProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func ContentType(p ContentTypeProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "content-type", props: a, void: false, children: children}
}
