// Code generated by htmlgen; DO NOT EDIT.
package html

type ContentSecurityPolicyProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func ContentSecurityPolicy(p ContentSecurityPolicyProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "content-security-policy", props: a, void: false, children: children}
}
