// Code generated by htmlgen; DO NOT EDIT.
package html

type ControlslistProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Controlslist(p ControlslistProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "controlslist", props: a, void: false, children: children}
}
