// Code generated by htmlgen; DO NOT EDIT.
package html

type CoverProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Cover(p CoverProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "cover", props: a, void: false, children: children}
}
