// Code generated by htmlgen; DO NOT EDIT.
package html

type CredentiallessProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Credentialless(p CredentiallessProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "credentialless", props: a, void: false, children: children}
}
