// Code generated by htmlgen; DO NOT EDIT.
package html

type CrossOriginIsolatedProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func CrossOriginIsolated(p CrossOriginIsolatedProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "cross-origin-isolated", props: a, void: false, children: children}
}
