// Code generated by htmlgen; DO NOT EDIT.
package html

type CrossoriginProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Crossorigin(p CrossoriginProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "crossorigin", props: a, void: false, children: children}
}
