// Code generated by htmlgen; DO NOT EDIT.
package html

type CspProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Csp(p CspProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "csp", props: a, void: false, children: children}
}
