// Code generated by htmlgen; DO NOT EDIT.
package html

type DataProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Data(p DataProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "data", props: a, void: false, children: children}
}
