// Code generated by htmlgen; DO NOT EDIT.
package html

type DatetimeProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Datetime(p DatetimeProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "datetime", props: a, void: false, children: children}
}
