// Code generated by htmlgen; DO NOT EDIT.
package html

type DdProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Dd(p DdProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "dd", props: a, void: false, children: children}
}
