// Code generated by htmlgen; DO NOT EDIT.
package html

type DeclareProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Declare(p DeclareProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "declare", props: a, void: false, children: children}
}
