// Code generated by htmlgen; DO NOT EDIT.
package html

type DecodingProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Decoding(p DecodingProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "decoding", props: a, void: false, children: children}
}
