// Code generated by htmlgen; DO NOT EDIT.
package html

type DefaultProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Default(p DefaultProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "default", props: a, void: false, children: children}
}
