// Code generated by htmlgen; DO NOT EDIT.
package html

type DescriptionsProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Descriptions(p DescriptionsProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "descriptions", props: a, void: false, children: children}
}
