// Code generated by htmlgen; DO NOT EDIT.
package html

type DialogProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Dialog(p DialogProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "dialog", props: a, void: false, children: children}
}
