// Code generated by htmlgen; DO NOT EDIT.
package html

type DirProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Dir(p DirProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "dir", props: a, void: false, children: children}
}
