// Code generated by htmlgen; DO NOT EDIT.
package html

type DirectionProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Direction(p DirectionProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "direction", props: a, void: false, children: children}
}
