// Code generated by htmlgen; DO NOT EDIT.
package html

type DirnameProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Dirname(p DirnameProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "dirname", props: a, void: false, children: children}
}
