// Code generated by htmlgen; DO NOT EDIT.
package html

type DisableremoteplaybackProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Disableremoteplayback(p DisableremoteplaybackProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "disableremoteplayback", props: a, void: false, children: children}
}
