// Code generated by htmlgen; DO NOT EDIT.
package html

type DisablesInvalidValuesInPickerUiProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func DisablesInvalidValuesInPickerUi(p DisablesInvalidValuesInPickerUiProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "disables_invalid_values_in_picker_ui", props: a, void: false, children: children}
}
