// Code generated by htmlgen; DO NOT EDIT.
package html

type DisabledProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Disabled(p DisabledProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "disabled", props: a, void: false, children: children}
}
