// Code generated by htmlgen; DO NOT EDIT.
package html

type DisablepictureinpictureProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Disablepictureinpicture(p DisablepictureinpictureProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "disablepictureinpicture", props: a, void: false, children: children}
}
