// Code generated by htmlgen; DO NOT EDIT.
package html

type DisplayListItemProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func DisplayListItem(p DisplayListItemProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "display_list_item", props: a, void: false, children: children}
}
