// Code generated by htmlgen; DO NOT EDIT.
package html

type DisplayCaptureProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func DisplayCapture(p DisplayCaptureProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "display-capture", props: a, void: false, children: children}
}
