// Code generated by htmlgen; DO NOT EDIT.
package html

type DlProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Dl(p DlProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "dl", props: a, void: false, children: children}
}
