// Code generated by htmlgen; DO NOT EDIT.
package html

type DnsPrefetchProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func DnsPrefetch(p DnsPrefetchProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "dns-prefetch", props: a, void: false, children: children}
}
