// Code generated by htmlgen; DO NOT EDIT.
package html

type DownloadProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Download(p DownloadProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "download", props: a, void: false, children: children}
}
