// Code generated by htmlgen; DO NOT EDIT.
package html

type EagernessProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Eagerness(p EagernessProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "eagerness", props: a, void: false, children: children}
}
