// Code generated by htmlgen; DO NOT EDIT.
package html

type Ed25519PublicKeyProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Ed25519PublicKey(p Ed25519PublicKeyProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "ed25519_public_key", props: a, void: false, children: children}
}
