// Code generated by htmlgen; DO NOT EDIT.
package html

type EmProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Em(p EmProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "em", props: a, void: false, children: children}
}
