// Code generated by htmlgen; DO NOT EDIT.
package html

type EmbedProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Embed(p EmbedProps) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "embed", props: a, void: true}
}
