// Code generated by htmlgen; DO NOT EDIT.
package html

type EncryptedMediaProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func EncryptedMedia(p EncryptedMediaProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "encrypted-media", props: a, void: false, children: children}
}
