// Code generated by htmlgen; DO NOT EDIT.
package html

type EnctypeProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Enctype(p EnctypeProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "enctype", props: a, void: false, children: children}
}
