// Code generated by htmlgen; DO NOT EDIT.
package html

type ExpectProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Expect(p ExpectProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "expect", props: a, void: false, children: children}
}
