// Code generated by htmlgen; DO NOT EDIT.
package html

type ExpectsNoVarySearchProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func ExpectsNoVarySearch(p ExpectsNoVarySearchProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "expects_no_vary_search", props: a, void: false, children: children}
}
