// Code generated by htmlgen; DO NOT EDIT.
package html

type FaceProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Face(p FaceProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "face", props: a, void: false, children: children}
}
