// Code generated by htmlgen; DO NOT EDIT.
package html

type FetchpriorityProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Fetchpriority(p FetchpriorityProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "fetchpriority", props: a, void: false, children: children}
}
