// Code generated by htmlgen; DO NOT EDIT.
package html

type FieldsetProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Fieldset(p FieldsetProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "fieldset", props: a, void: false, children: children}
}
