// Code generated by htmlgen; DO NOT EDIT.
package html

type FigcaptionProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Figcaption(p FigcaptionProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "figcaption", props: a, void: false, children: children}
}
