// Code generated by htmlgen; DO NOT EDIT.
package html

type FigureProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Figure(p FigureProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "figure", props: a, void: false, children: children}
}
