// Code generated by htmlgen; DO NOT EDIT.
package html

type FooterProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Footer(p FooterProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "footer", props: a, void: false, children: children}
}
