// Code generated by htmlgen; DO NOT EDIT.
package html

type ForProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func For(p ForProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "for", props: a, void: false, children: children}
}
