// Code generated by htmlgen; DO NOT EDIT.
package html

type ForbidDataJavascriptUrlsProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func ForbidDataJavascriptUrls(p ForbidDataJavascriptUrlsProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "forbid_data_javascript_urls", props: a, void: false, children: children}
}
