// Code generated by htmlgen; DO NOT EDIT.
package html

type FormactionProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Formaction(p FormactionProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "formaction", props: a, void: false, children: children}
}
