// Code generated by htmlgen; DO NOT EDIT.
package html

type FormtargetProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Formtarget(p FormtargetProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "formtarget", props: a, void: false, children: children}
}
