// Code generated by htmlgen; DO NOT EDIT.
package html

type FormenctypeProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Formenctype(p FormenctypeProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "formenctype", props: a, void: false, children: children}
}
