// Code generated by htmlgen; DO NOT EDIT.
package html

type FormmethodProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Formmethod(p FormmethodProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "formmethod", props: a, void: false, children: children}
}
