// Code generated by htmlgen; DO NOT EDIT.
package html

type FrameborderProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Frameborder(p FrameborderProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "frameborder", props: a, void: false, children: children}
}
