// Code generated by htmlgen; DO NOT EDIT.
package html

type FramesetProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Frameset(p FramesetProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "frameset", props: a, void: false, children: children}
}
