// Code generated by htmlgen; DO NOT EDIT.
package html

type FullscreenProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Fullscreen(p FullscreenProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "fullscreen", props: a, void: false, children: children}
}
