// Code generated by htmlgen; DO NOT EDIT.
package html

type GeolocationProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Geolocation(p GeolocationProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "geolocation", props: a, void: false, children: children}
}
