// Code generated by htmlgen; DO NOT EDIT.
package html

type GyroscopeProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Gyroscope(p GyroscopeProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "gyroscope", props: a, void: false, children: children}
}
