// Code generated by htmlgen; DO NOT EDIT.
package html

type H2Props struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func H2(p H2Props, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "h2", props: a, void: false, children: children}
}
