// Code generated by htmlgen; DO NOT EDIT.
package html

type H3Props struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func H3(p H3Props, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "h3", props: a, void: false, children: children}
}
