// Code generated by htmlgen; DO NOT EDIT.
package html

type H4Props struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func H4(p H4Props, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "h4", props: a, void: false, children: children}
}
