// Code generated by htmlgen; DO NOT EDIT.
package html

type H6Props struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func H6(p H6Props, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "h6", props: a, void: false, children: children}
}
