// Code generated by htmlgen; DO NOT EDIT.
package html

type HardProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Hard(p HardProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "hard", props: a, void: false, children: children}
}
