// Code generated by htmlgen; DO NOT EDIT.
package html

type HeaderProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Header(p HeaderProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "header", props: a, void: false, children: children}
}
