// Code generated by htmlgen; DO NOT EDIT.
package html

type HeadersProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Headers(p HeadersProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "headers", props: a, void: false, children: children}
}
