// Code generated by htmlgen; DO NOT EDIT.
package html

type HeadProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Head(p HeadProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "head", props: a, void: false, children: children}
}
