// Code generated by htmlgen; DO NOT EDIT.
package html

type HeightProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Height(p HeightProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "height", props: a, void: false, children: children}
}
