// Code generated by htmlgen; DO NOT EDIT.
package html

type HidProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Hid(p HidProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "hid", props: a, void: false, children: children}
}
