// Code generated by htmlgen; DO NOT EDIT.
package html

type HighProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func High(p HighProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "high", props: a, void: false, children: children}
}
