// Code generated by htmlgen; DO NOT EDIT.
package html

type HrProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Hr(p HrProps) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "hr", props: a, void: true}
}
