// Code generated by htmlgen; DO NOT EDIT.
package html

type HrInSelectProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func HrInSelect(p HrInSelectProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "hr_in_select", props: a, void: false, children: children}
}
