// Code generated by htmlgen; DO NOT EDIT.
package html

type HrefProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Href(p HrefProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "href", props: a, void: false, children: children}
}
