// Code generated by htmlgen; DO NOT EDIT.
package html

type HrefSmsProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func HrefSms(p HrefSmsProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "href_sms", props: a, void: false, children: children}
}
