// Code generated by htmlgen; DO NOT EDIT.
package html

type HreflangProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Hreflang(p HreflangProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "hreflang", props: a, void: false, children: children}
}
