// Code generated by htmlgen; DO NOT EDIT.
package html

type HreftranslateProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Hreftranslate(p HreftranslateProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "hreftranslate", props: a, void: false, children: children}
}
