// Code generated by htmlgen; DO NOT EDIT.
package html

type HrefTopProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func HrefTop(p HrefTopProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "href_top", props: a, void: false, children: children}
}
