// Code generated by htmlgen; DO NOT EDIT.
package html

type HspaceProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Hspace(p HspaceProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "hspace", props: a, void: false, children: children}
}
