// Code generated by htmlgen; DO NOT EDIT.
package html

type HttpEquivProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func HttpEquiv(p HttpEquivProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "http-equiv", props: a, void: false, children: children}
}
