// Code generated by htmlgen; DO NOT EDIT.
package html

type IconProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Icon(p IconProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "icon", props: a, void: false, children: children}
}
