// Code generated by htmlgen; DO NOT EDIT.
package html

type IdentityCredentialsGetProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func IdentityCredentialsGet(p IdentityCredentialsGetProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "identity-credentials-get", props: a, void: false, children: children}
}
