// Code generated by htmlgen; DO NOT EDIT.
package html

type IdleDetectionProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func IdleDetection(p IdleDetectionProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "idle-detection", props: a, void: false, children: children}
}
