// Code generated by htmlgen; DO NOT EDIT.
package html

type IframeProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Iframe(p IframeProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "iframe", props: a, void: false, children: children}
}
