// Code generated by htmlgen; DO NOT EDIT.
package html

type ImagesrcsetProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Imagesrcset(p ImagesrcsetProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "imagesrcset", props: a, void: false, children: children}
}
