// Code generated by htmlgen; DO NOT EDIT.
package html

type ImplicitAnchorReferenceProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func ImplicitAnchorReference(p ImplicitAnchorReferenceProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "implicit_anchor_reference", props: a, void: false, children: children}
}
