// Code generated by htmlgen; DO NOT EDIT.
package html

type ImportmapProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Importmap(p ImportmapProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "importmap", props: a, void: false, children: children}
}
