// Code generated by htmlgen; DO NOT EDIT.
package html

type InitialScaleProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func InitialScale(p InitialScaleProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "initial-scale", props: a, void: false, children: children}
}
