// Code generated by htmlgen; DO NOT EDIT.
package html

type InputTypeDateProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func InputTypeDate(p InputTypeDateProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "input_type_date", props: a, void: false, children: children}
}
