// Code generated by htmlgen; DO NOT EDIT.
package html

type InputTypeTimeProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func InputTypeTime(p InputTypeTimeProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "input_type_time", props: a, void: false, children: children}
}
