// Code generated by htmlgen; DO NOT EDIT.
package html

type InputTypeColorProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func InputTypeColor(p InputTypeColorProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "input_type_color", props: a, void: false, children: children}
}
