// Code generated by htmlgen; DO NOT EDIT.
package html

type InputTypeUrlProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func InputTypeUrl(p InputTypeUrlProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "input_type_url", props: a, void: false, children: children}
}
