// Code generated by htmlgen; DO NOT EDIT.
package html

type InputTypeRangeProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func InputTypeRange(p InputTypeRangeProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "input_type_range", props: a, void: false, children: children}
}
