// Code generated by htmlgen; DO NOT EDIT.
package html

type InputTypeSearchProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func InputTypeSearch(p InputTypeSearchProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "input_type_search", props: a, void: false, children: children}
}
