// Code generated by htmlgen; DO NOT EDIT.
package html

type InsecureLoginHandlingProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func InsecureLoginHandling(p InsecureLoginHandlingProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "insecure_login_handling", props: a, void: false, children: children}
}
