// Code generated by htmlgen; DO NOT EDIT.
package html

type InteractiveWidgetProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func InteractiveWidget(p InteractiveWidgetProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "interactive-widget", props: a, void: false, children: children}
}
