// Code generated by htmlgen; DO NOT EDIT.
package html

type IntegrityProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Integrity(p IntegrityProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "integrity", props: a, void: false, children: children}
}
