// Code generated by htmlgen; DO NOT EDIT.
package html

type InterestforProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Interestfor(p InterestforProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "interestfor", props: a, void: false, children: children}
}
