// Code generated by htmlgen; DO NOT EDIT.
package html

type KbdProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Kbd(p KbdProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "kbd", props: a, void: false, children: children}
}
