// Code generated by htmlgen; DO NOT EDIT.
package html

type KindProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Kind(p KindProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "kind", props: a, void: false, children: children}
}
