// Code generated by htmlgen; DO NOT EDIT.
package html

type LabelProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Label(p LabelProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "label", props: a, void: false, children: children}
}
