// Code generated by htmlgen; DO NOT EDIT.
package html

type LabeledValuesProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func LabeledValues(p LabeledValuesProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "labeled_values", props: a, void: false, children: children}
}
