// Code generated by htmlgen; DO NOT EDIT.
package html

type LeftmarginProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Leftmargin(p LeftmarginProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "leftmargin", props: a, void: false, children: children}
}
