// Code generated by htmlgen; DO NOT EDIT.
package html

type LegendProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Legend(p LegendProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "legend", props: a, void: false, children: children}
}
