// Code generated by htmlgen; DO NOT EDIT.
package html

type LiProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Li(p LiProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "li", props: a, void: false, children: children}
}
