// Code generated by htmlgen; DO NOT EDIT.
package html

type LineBreaksProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func LineBreaks(p LineBreaksProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "line_breaks", props: a, void: false, children: children}
}
