// Code generated by htmlgen; DO NOT EDIT.
package html

type LinkProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Link(p LinkProps) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "link", props: a, void: true}
}
