// Code generated by htmlgen; DO NOT EDIT.
package html

type ListProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func List(p ListProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "list", props: a, void: false, children: children}
}
