// Code generated by htmlgen; DO NOT EDIT.
package html

type LoadingProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Loading(p LoadingProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "loading", props: a, void: false, children: children}
}
