// Code generated by htmlgen; DO NOT EDIT.
package html

type LocalFontsProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func LocalFonts(p LocalFontsProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "local-fonts", props: a, void: false, children: children}
}
