// Code generated by htmlgen; DO NOT EDIT.
package html

type LongdescProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Longdesc(p LongdescProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "longdesc", props: a, void: false, children: children}
}
