// Code generated by htmlgen; DO NOT EDIT.
package html

type LowProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Low(p LowProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "low", props: a, void: false, children: children}
}
