// Code generated by htmlgen; DO NOT EDIT.
package html

type MagnetometerProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Magnetometer(p MagnetometerProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "magnetometer", props: a, void: false, children: children}
}
