// Code generated by htmlgen; DO NOT EDIT.
package html

type ManifestProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Manifest(p ManifestProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "manifest", props: a, void: false, children: children}
}
