// Code generated by htmlgen; DO NOT EDIT.
package html

type MarginheightProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Marginheight(p MarginheightProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "marginheight", props: a, void: false, children: children}
}
