// Code generated by htmlgen; DO NOT EDIT.
package html

type MarginwidthProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Marginwidth(p MarginwidthProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "marginwidth", props: a, void: false, children: children}
}
