// Code generated by htmlgen; DO NOT EDIT.
package html

type MarkProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Mark(p MarkProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "mark", props: a, void: false, children: children}
}
