// Code generated by htmlgen; DO NOT EDIT.
package html

type MaxProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Max(p MaxProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "max", props: a, void: false, children: children}
}
