// Code generated by htmlgen; DO NOT EDIT.
package html

type MaximumScaleProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func MaximumScale(p MaximumScaleProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "maximum-scale", props: a, void: false, children: children}
}
