// Code generated by htmlgen; DO NOT EDIT.
package html

type MaxlengthProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Maxlength(p MaxlengthProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "maxlength", props: a, void: false, children: children}
}
