// Code generated by htmlgen; DO NOT EDIT.
package html

type MediaProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Media(p MediaProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "media", props: a, void: false, children: children}
}
