// Code generated by htmlgen; DO NOT EDIT.
package html

type MenuProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Menu(p MenuProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "menu", props: a, void: false, children: children}
}
