// Code generated by htmlgen; DO NOT EDIT.
package html

type MetaProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Meta(p MetaProps) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "meta", props: a, void: true}
}
