// Code generated by htmlgen; DO NOT EDIT.
package html

type MethodProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Method(p MethodProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "method", props: a, void: false, children: children}
}
