// Code generated by htmlgen; DO NOT EDIT.
package html

type MicrophoneProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Microphone(p MicrophoneProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "microphone", props: a, void: false, children: children}
}
