// Code generated by htmlgen; DO NOT EDIT.
package html

type MidiProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Midi(p MidiProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "midi", props: a, void: false, children: children}
}
