// Code generated by htmlgen; DO NOT EDIT.
package html

type MinProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Min(p MinProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "min", props: a, void: false, children: children}
}
