// Code generated by htmlgen; DO NOT EDIT.
package html

type MinimumScaleProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func MinimumScale(p MinimumScaleProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "minimum-scale", props: a, void: false, children: children}
}
