// Code generated by htmlgen; DO NOT EDIT.
package html

type ModelProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Model(p ModelProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "model", props: a, void: false, children: children}
}
