// Code generated by htmlgen; DO NOT EDIT.
package html

type ModulepreloadProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Modulepreload(p ModulepreloadProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "modulepreload", props: a, void: false, children: children}
}
