// Code generated by htmlgen; DO NOT EDIT.
package html

type ModuleProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Module(p ModuleProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "module", props: a, void: false, children: children}
}
