// Code generated by htmlgen; DO NOT EDIT.
package html

type MozOpaqueProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func MozOpaque(p MozOpaqueProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "moz-opaque", props: a, void: false, children: children}
}
