// Code generated by htmlgen; DO NOT EDIT.
package html

type MultipleProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Multiple(p MultipleProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "multiple", props: a, void: false, children: children}
}
