// Code generated by htmlgen; DO NOT EDIT.
package html

type MultipleImportMapsProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func MultipleImportMaps(p MultipleImportMapsProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "multiple_import_maps", props: a, void: false, children: children}
}
