// Code generated by htmlgen; DO NOT EDIT.
package html

type MutedProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Muted(p MutedProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "muted", props: a, void: false, children: children}
}
