// Code generated by htmlgen; DO NOT EDIT.
package html

type NameProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Name(p NameProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "name", props: a, void: false, children: children}
}
