// Code generated by htmlgen; DO NOT EDIT.
package html

type NewPasswordProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func NewPassword(p NewPasswordProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "new-password", props: a, void: false, children: children}
}
