// Code generated by htmlgen; DO NOT EDIT.
package html

type NoReferrerWhenDowngradeProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func NoReferrerWhenDowngrade(p NoReferrerWhenDowngradeProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "no-referrer-when-downgrade", props: a, void: false, children: children}
}
