// Code generated by htmlgen; DO NOT EDIT.
package html

type NoUaStylesInArticleAsideNavSectionProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func NoUaStylesInArticleAsideNavSection(p NoUaStylesInArticleAsideNavSectionProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "no_ua_styles_in_article_aside_nav_section", props: a, void: false, children: children}
}
