// Code generated by htmlgen; DO NOT EDIT.
package html

type NobrProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Nobr(p NobrProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "nobr", props: a, void: false, children: children}
}
