// Code generated by htmlgen; DO NOT EDIT.
package html

type NoembedProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Noembed(p NoembedProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "noembed", props: a, void: false, children: children}
}
