// Code generated by htmlgen; DO NOT EDIT.
package html

type NohrefProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Nohref(p NohrefProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "nohref", props: a, void: false, children: children}
}
