// Code generated by htmlgen; DO NOT EDIT.
package html

type NomoduleProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Nomodule(p NomoduleProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "nomodule", props: a, void: false, children: children}
}
