// Code generated by htmlgen; DO NOT EDIT.
package html

type NoopenerProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Noopener(p NoopenerProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "noopener", props: a, void: false, children: children}
}
