// Code generated by htmlgen; DO NOT EDIT.
package html

type NoreferrerProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Noreferrer(p NoreferrerProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "noreferrer", props: a, void: false, children: children}
}
