// Code generated by htmlgen; DO NOT EDIT.
package html

type NoresizeProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Noresize(p NoresizeProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "noresize", props: a, void: false, children: children}
}
