// Code generated by htmlgen; DO NOT EDIT.
package html

type NoshadeProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Noshade(p NoshadeProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "noshade", props: a, void: false, children: children}
}
