// Code generated by htmlgen; DO NOT EDIT.
package html

type NovalidateProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Novalidate(p NovalidateProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "novalidate", props: a, void: false, children: children}
}
