// Code generated by htmlgen; DO NOT EDIT.
package html

type OneTimeCodeProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func OneTimeCode(p OneTimeCodeProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "one-time-code", props: a, void: false, children: children}
}
