// Code generated by htmlgen; DO NOT EDIT.
package html

type OpenProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Open(p OpenProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "open", props: a, void: false, children: children}
}
