// Code generated by htmlgen; DO NOT EDIT.
package html

type OptgroupProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Optgroup(p OptgroupProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "optgroup", props: a, void: false, children: children}
}
