// Code generated by htmlgen; DO NOT EDIT.
package html

type OptimumProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Optimum(p OptimumProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "optimum", props: a, void: false, children: children}
}
