// Code generated by htmlgen; DO NOT EDIT.
package html

type OptionProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Option(p OptionProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "option", props: a, void: false, children: children}
}
