// Code generated by htmlgen; DO NOT EDIT.
package html

type OriginWhenCrossOriginProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func OriginWhenCrossOrigin(p OriginWhenCrossOriginProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "origin-when-cross-origin", props: a, void: false, children: children}
}
