// Code generated by htmlgen; DO NOT EDIT.
package html

type OtpCredentialsProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func OtpCredentials(p OtpCredentialsProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "otp-credentials", props: a, void: false, children: children}
}
