// Code generated by htmlgen; DO NOT EDIT.
package html

type OverlaysContentProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func OverlaysContent(p OverlaysContentProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "overlays-content", props: a, void: false, children: children}
}
