// Code generated by htmlgen; DO NOT EDIT.
package html

type PProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func P(p PProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "p", props: a, void: false, children: children}
}
