// Code generated by htmlgen; DO NOT EDIT.
package html

type ParamProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Param(p ParamProps) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "param", props: a, void: true}
}
