// Code generated by htmlgen; DO NOT EDIT.
package html

type PatternProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Pattern(p PatternProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "pattern", props: a, void: false, children: children}
}
