// Code generated by htmlgen; DO NOT EDIT.
package html

type PaymentProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Payment(p PaymentProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "payment", props: a, void: false, children: children}
}
