// Code generated by htmlgen; DO NOT EDIT.
package html

type PictureInPictureProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func PictureInPicture(p PictureInPictureProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "picture-in-picture", props: a, void: false, children: children}
}
