// Code generated by htmlgen; DO NOT EDIT.
package html

type PictureProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Picture(p PictureProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "picture", props: a, void: false, children: children}
}
