// Code generated by htmlgen; DO NOT EDIT.
package html

type PingProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Ping(p PingProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "ping", props: a, void: false, children: children}
}
