// Code generated by htmlgen; DO NOT EDIT.
package html

type PlaysinlineProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Playsinline(p PlaysinlineProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "playsinline", props: a, void: false, children: children}
}
