// Code generated by htmlgen; DO NOT EDIT.
package html

type PopovertargetactionProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Popovertargetaction(p PopovertargetactionProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "popovertargetaction", props: a, void: false, children: children}
}
