// Code generated by htmlgen; DO NOT EDIT.
package html

type PosterProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Poster(p PosterProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "poster", props: a, void: false, children: children}
}
