// Code generated by htmlgen; DO NOT EDIT.
package html

type PrefetchProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Prefetch(p PrefetchProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "prefetch", props: a, void: false, children: children}
}
