// Code generated by htmlgen; DO NOT EDIT.
package html

type PreloadProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Preload(p PreloadProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "preload", props: a, void: false, children: children}
}
