// Code generated by htmlgen; DO NOT EDIT.
package html

type PrerenderProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Prerender(p PrerenderProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "prerender", props: a, void: false, children: children}
}
