// Code generated by htmlgen; DO NOT EDIT.
package html

type PrivateTokenProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func PrivateToken(p PrivateTokenProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "privateToken", props: a, void: false, children: children}
}
