// Code generated by htmlgen; DO NOT EDIT.
package html

type PublickeyCredentialsGetProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func PublickeyCredentialsGet(p PublickeyCredentialsGetProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "publickey-credentials-get", props: a, void: false, children: children}
}
