// Code generated by htmlgen; DO NOT EDIT.
package html

type RbProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Rb(p RbProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "rb", props: a, void: false, children: children}
}
