// Code generated by htmlgen; DO NOT EDIT.
package html

type ReadonlyProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Readonly(p ReadonlyProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "readonly", props: a, void: false, children: children}
}
