// Code generated by htmlgen; DO NOT EDIT.
package html

type ReferrerpolicyProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Referrerpolicy(p ReferrerpolicyProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "referrerpolicy", props: a, void: false, children: children}
}
