// Code generated by htmlgen; DO NOT EDIT.
package html

type ReferrerProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Referrer(p ReferrerProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "referrer", props: a, void: false, children: children}
}
