// Code generated by htmlgen; DO NOT EDIT.
package html

type ReferrerPolicyProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func ReferrerPolicy(p ReferrerPolicyProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "referrer_policy", props: a, void: false, children: children}
}
