// Code generated by htmlgen; DO NOT EDIT.
package html

type RefreshProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Refresh(p RefreshProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "refresh", props: a, void: false, children: children}
}
