// Code generated by htmlgen; DO NOT EDIT.
package html

type RelProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Rel(p RelProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "rel", props: a, void: false, children: children}
}
