// Code generated by htmlgen; DO NOT EDIT.
package html

type RelativeToProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func RelativeTo(p RelativeToProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "relative_to", props: a, void: false, children: children}
}
