// Code generated by htmlgen; DO NOT EDIT.
package html

type RelativeUrlProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func RelativeUrl(p RelativeUrlProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "relative_url", props: a, void: false, children: children}
}
