// Code generated by htmlgen; DO NOT EDIT.
package html

type RequiresMutedAudioProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func RequiresMutedAudio(p RequiresMutedAudioProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "requires_muted_audio", props: a, void: false, children: children}
}
