// Code generated by htmlgen; DO NOT EDIT.
package html

type RequestCloseProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func RequestClose(p RequestCloseProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "request-close", props: a, void: false, children: children}
}
