// Code generated by htmlgen; DO NOT EDIT.
package html

type RequiredProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Required(p RequiredProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "required", props: a, void: false, children: children}
}
