// Code generated by htmlgen; DO NOT EDIT.
package html

type RequiresProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Requires(p RequiresProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "requires", props: a, void: false, children: children}
}
