// Code generated by htmlgen; DO NOT EDIT.
package html

type ResizesContentProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func ResizesContent(p ResizesContentProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "resizes-content", props: a, void: false, children: children}
}
