// Code generated by htmlgen; DO NOT EDIT.
package html

type ResizesVisualProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func ResizesVisual(p ResizesVisualProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "resizes-visual", props: a, void: false, children: children}
}
