// Code generated by htmlgen; DO NOT EDIT.
package html

type ResponsiveEmbeddedSizingProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func ResponsiveEmbeddedSizing(p ResponsiveEmbeddedSizingProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "responsive-embedded-sizing", props: a, void: false, children: children}
}
