// Code generated by htmlgen; DO NOT EDIT.
package html

type RevProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Rev(p RevProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "rev", props: a, void: false, children: children}
}
