// Code generated by htmlgen; DO NOT EDIT.
package html

type ReversedProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Reversed(p ReversedProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "reversed", props: a, void: false, children: children}
}
