// Code generated by htmlgen; DO NOT EDIT.
package html

type RightmarginProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Rightmargin(p RightmarginProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "rightmargin", props: a, void: false, children: children}
}
