// Code generated by htmlgen; DO NOT EDIT.
package html

type RowsProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Rows(p RowsProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "rows", props: a, void: false, children: children}
}
