// Code generated by htmlgen; DO NOT EDIT.
package html

type RowspanZeroProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func RowspanZero(p RowspanZeroProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "rowspan_zero", props: a, void: false, children: children}
}
