// Code generated by htmlgen; DO NOT EDIT.
package html

type RpProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Rp(p RpProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "rp", props: a, void: false, children: children}
}
