// Code generated by htmlgen; DO NOT EDIT.
package html

type RtProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Rt(p RtProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "rt", props: a, void: false, children: children}
}
