// Code generated by htmlgen; DO NOT EDIT.
package html

type RtcProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Rtc(p RtcProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "rtc", props: a, void: false, children: children}
}
