// Code generated by htmlgen; DO NOT EDIT.
package html

type RubyProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Ruby(p RubyProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "ruby", props: a, void: false, children: children}
}
