// Code generated by htmlgen; DO NOT EDIT.
package html

type SProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func S(p SProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "s", props: a, void: false, children: children}
}
