// Code generated by htmlgen; DO NOT EDIT.
package html

type SampProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Samp(p SampProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "samp", props: a, void: false, children: children}
}
