// Code generated by htmlgen; DO NOT EDIT.
package html

type SandboxProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Sandbox(p SandboxProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "sandbox", props: a, void: false, children: children}
}
