// Code generated by htmlgen; DO NOT EDIT.
package html

type SchemeProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Scheme(p SchemeProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "scheme", props: a, void: false, children: children}
}
