// Code generated by htmlgen; DO NOT EDIT.
package html

type ScopeProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Scope(p ScopeProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "scope", props: a, void: false, children: children}
}
