// Code generated by htmlgen; DO NOT EDIT.
package html

type ScreenWakeLockProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func ScreenWakeLock(p ScreenWakeLockProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "screen-wake-lock", props: a, void: false, children: children}
}
