// Code generated by htmlgen; DO NOT EDIT.
package html

type ScrollingProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Scrolling(p ScrollingProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "scrolling", props: a, void: false, children: children}
}
