// Code generated by htmlgen; DO NOT EDIT.
package html

type ScrolldelayProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Scrolldelay(p ScrolldelayProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "scrolldelay", props: a, void: false, children: children}
}
