// Code generated by htmlgen; DO NOT EDIT.
package html

type ScrollamountProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Scrollamount(p ScrollamountProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "scrollamount", props: a, void: false, children: children}
}
