// Code generated by htmlgen; DO NOT EDIT.
package html

type SearchMatchOpensProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func SearchMatchOpens(p SearchMatchOpensProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "search_match_opens", props: a, void: false, children: children}
}
