// Code generated by htmlgen; DO NOT EDIT.
package html

type SectionProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Section(p SectionProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "section", props: a, void: false, children: children}
}
