// Code generated by htmlgen; DO NOT EDIT.
package html

type SelectedProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Selected(p SelectedProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "selected", props: a, void: false, children: children}
}
