// Code generated by htmlgen; DO NOT EDIT.
package html

type ShadowrootclonableProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Shadowrootclonable(p ShadowrootclonableProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "shadowrootclonable", props: a, void: false, children: children}
}
