// Code generated by htmlgen; DO NOT EDIT.
package html

type ShadowrootcustomelementregistryProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Shadowrootcustomelementregistry(p ShadowrootcustomelementregistryProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "shadowrootcustomelementregistry", props: a, void: false, children: children}
}
