// Code generated by htmlgen; DO NOT EDIT.
package html

type ShadowrootslotassignmentProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Shadowrootslotassignment(p ShadowrootslotassignmentProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "shadowrootslotassignment", props: a, void: false, children: children}
}
