// Code generated by htmlgen; DO NOT EDIT.
package html

type ShadowrootserializableProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Shadowrootserializable(p ShadowrootserializableProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "shadowrootserializable", props: a, void: false, children: children}
}
