// Code generated by htmlgen; DO NOT EDIT.
package html

type ShadowrootreferencetargetProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Shadowrootreferencetarget(p ShadowrootreferencetargetProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "shadowrootreferencetarget", props: a, void: false, children: children}
}
