// Code generated by htmlgen; DO NOT EDIT.
package html

type ShadowrootmodeProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Shadowrootmode(p ShadowrootmodeProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "shadowrootmode", props: a, void: false, children: children}
}
