// Code generated by htmlgen; DO NOT EDIT.
package html

type ShadowrootdelegatesfocusProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Shadowrootdelegatesfocus(p ShadowrootdelegatesfocusProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "shadowrootdelegatesfocus", props: a, void: false, children: children}
}
