// Code generated by htmlgen; DO NOT EDIT.
package html

type ShapeProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Shape(p ShapeProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "shape", props: a, void: false, children: children}
}
