// Code generated by htmlgen; DO NOT EDIT.
package html

type SizeProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Size(p SizeProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "size", props: a, void: false, children: children}
}
