// Code generated by htmlgen; DO NOT EDIT.
package html

type SlotProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Slot(p SlotProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "slot", props: a, void: false, children: children}
}
