// Code generated by htmlgen; DO NOT EDIT.
package html

type SmallProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Small(p SmallProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "small", props: a, void: false, children: children}
}
