// Code generated by htmlgen; DO NOT EDIT.
package html

type SourceOptionalProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func SourceOptional(p SourceOptionalProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "source_optional", props: a, void: false, children: children}
}
