// Code generated by htmlgen; DO NOT EDIT.
package html

type SpanProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Span(p SpanProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "span", props: a, void: false, children: children}
}
