// Code generated by htmlgen; DO NOT EDIT.
package html

type SpeakerSelectionProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func SpeakerSelection(p SpeakerSelectionProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "speaker-selection", props: a, void: false, children: children}
}
