// Code generated by htmlgen; DO NOT EDIT.
package html

type SpeculationrulesProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Speculationrules(p SpeculationrulesProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "speculationrules", props: a, void: false, children: children}
}
