// Code generated by htmlgen; DO NOT EDIT.
package html

type SrcProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Src(p SrcProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "src", props: a, void: false, children: children}
}
