// Code generated by htmlgen; DO NOT EDIT.
package html

type SrcdocProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Srcdoc(p SrcdocProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "srcdoc", props: a, void: false, children: children}
}
