// Code generated by htmlgen; DO NOT EDIT.
package html

type SrclangProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Srclang(p SrclangProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "srclang", props: a, void: false, children: children}
}
