// Code generated by htmlgen; DO NOT EDIT.
package html

type SrcsetProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Srcset(p SrcsetProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "srcset", props: a, void: false, children: children}
}
