// Code generated by htmlgen; DO NOT EDIT.
package html

type StagemodeProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Stagemode(p StagemodeProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "stagemode", props: a, void: false, children: children}
}
