// Code generated by htmlgen; DO NOT EDIT.
package html

type StandbyProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Standby(p StandbyProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "standby", props: a, void: false, children: children}
}
