// Code generated by htmlgen; DO NOT EDIT.
package html

type StepProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Step(p StepProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "step", props: a, void: false, children: children}
}
