// Code generated by htmlgen; DO NOT EDIT.
package html

type StorageAccessProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func StorageAccess(p StorageAccessProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "storage-access", props: a, void: false, children: children}
}
