// Code generated by htmlgen; DO NOT EDIT.
package html

type StrikeProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Strike(p StrikeProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "strike", props: a, void: false, children: children}
}
