// Code generated by htmlgen; DO NOT EDIT.
package html

type StrongProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Strong(p StrongProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "strong", props: a, void: false, children: children}
}
