// Code generated by htmlgen; DO NOT EDIT.
package html

type SummaryProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Summary(p SummaryProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "summary", props: a, void: false, children: children}
}
