// Code generated by htmlgen; DO NOT EDIT.
package html

type SupProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Sup(p SupProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "sup", props: a, void: false, children: children}
}
