// Code generated by htmlgen; DO NOT EDIT.
package html

type SwitchProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Switch(p SwitchProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "switch", props: a, void: false, children: children}
}
