// Code generated by htmlgen; DO NOT EDIT.
package html

type TableProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Table(p TableProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "table", props: a, void: false, children: children}
}
