// Code generated by htmlgen; DO NOT EDIT.
package html

type TagProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Tag(p TagProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "tag", props: a, void: false, children: children}
}
