// Code generated by htmlgen; DO NOT EDIT.
package html

type TargetHintProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func TargetHint(p TargetHintProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "target_hint", props: a, void: false, children: children}
}
