// Code generated by htmlgen; DO NOT EDIT.
package html

type TargetProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Target(p TargetProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "target", props: a, void: false, children: children}
}
