// Code generated by htmlgen; DO NOT EDIT.
package html

type TemplateProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Template(p TemplateProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "template", props: a, void: false, children: children}
}
