// Code generated by htmlgen; DO NOT EDIT.
package html

type TextFragmentsProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func TextFragments(p TextFragmentsProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "text_fragments", props: a, void: false, children: children}
}
