// Code generated by htmlgen; DO NOT EDIT.
package html

type TextScaleProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func TextScale(p TextScaleProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "text-scale", props: a, void: false, children: children}
}
