// Code generated by htmlgen; DO NOT EDIT.
package html

type TextareaProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Textarea(p TextareaProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "textarea", props: a, void: false, children: children}
}
