// Code generated by htmlgen; DO NOT EDIT.
package html

type TfootProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Tfoot(p TfootProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "tfoot", props: a, void: false, children: children}
}
