// Code generated by htmlgen; DO NOT EDIT.
package html

type TheadProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Thead(p TheadProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "thead", props: a, void: false, children: children}
}
