// Code generated by htmlgen; DO NOT EDIT.
package html

type ThemeColorProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func ThemeColor(p ThemeColorProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "theme-color", props: a, void: false, children: children}
}
