// Code generated by htmlgen; DO NOT EDIT.
package html

type TickMarksProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func TickMarks(p TickMarksProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "tick_marks", props: a, void: false, children: children}
}
