// Code generated by htmlgen; DO NOT EDIT.
package html

type TopmarginProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Topmargin(p TopmarginProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "topmargin", props: a, void: false, children: children}
}
