// Code generated by htmlgen; DO NOT EDIT.
package html

type TruespeedProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Truespeed(p TruespeedProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "truespeed", props: a, void: false, children: children}
}
