// Code generated by htmlgen; DO NOT EDIT.
package html

type TypeWeekProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func TypeWeek(p TypeWeekProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "type_week", props: a, void: false, children: children}
}
