// Code generated by htmlgen; DO NOT EDIT.
package html

type TypeTimeProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func TypeTime(p TypeTimeProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "type_time", props: a, void: false, children: children}
}
