// Code generated by htmlgen; DO NOT EDIT.
package html

type TypeTextProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func TypeText(p TypeTextProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "type_text", props: a, void: false, children: children}
}
