// Code generated by htmlgen; DO NOT EDIT.
package html

type TypeUrlProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func TypeUrl(p TypeUrlProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "type_url", props: a, void: false, children: children}
}
