// Code generated by htmlgen; DO NOT EDIT.
package html

type TypeFileProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func TypeFile(p TypeFileProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "type_file", props: a, void: false, children: children}
}
