// Code generated by htmlgen; DO NOT EDIT.
package html

type TypeSubmitProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func TypeSubmit(p TypeSubmitProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "type_submit", props: a, void: false, children: children}
}
