// Code generated by htmlgen; DO NOT EDIT.
package html

type TypeImageProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func TypeImage(p TypeImageProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "type_image", props: a, void: false, children: children}
}
