// Code generated by htmlgen; DO NOT EDIT.
package html

type TypeProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Type(p TypeProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "type", props: a, void: false, children: children}
}
