// Code generated by htmlgen; DO NOT EDIT.
package html

type TypeMonthProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func TypeMonth(p TypeMonthProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "type_month", props: a, void: false, children: children}
}
