// Code generated by htmlgen; DO NOT EDIT.
package html

type TypeNumberProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func TypeNumber(p TypeNumberProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "type_number", props: a, void: false, children: children}
}
