// Code generated by htmlgen; DO NOT EDIT.
package html

type TypeSearchProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func TypeSearch(p TypeSearchProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "type_search", props: a, void: false, children: children}
}
