// Code generated by htmlgen; DO NOT EDIT.
package html

type TypePasswordProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func TypePassword(p TypePasswordProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "type_password", props: a, void: false, children: children}
}
