// Code generated by htmlgen; DO NOT EDIT.
package html

type TypeEmailProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func TypeEmail(p TypeEmailProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "type_email", props: a, void: false, children: children}
}
