// Code generated by htmlgen; DO NOT EDIT.
package html

type TypeTelProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func TypeTel(p TypeTelProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "type_tel", props: a, void: false, children: children}
}
