// Code generated by htmlgen; DO NOT EDIT.
package html

type TypeDatetimeLocalProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func TypeDatetimeLocal(p TypeDatetimeLocalProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "type_datetime-local", props: a, void: false, children: children}
}
