// Code generated by htmlgen; DO NOT EDIT.
package html

type TypeHiddenProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func TypeHidden(p TypeHiddenProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "type_hidden", props: a, void: false, children: children}
}
