// Code generated by htmlgen; DO NOT EDIT.
package html

type TypeResetProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func TypeReset(p TypeResetProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "type_reset", props: a, void: false, children: children}
}
