// Code generated by htmlgen; DO NOT EDIT.
package html

type TypeColorProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func TypeColor(p TypeColorProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "type_color", props: a, void: false, children: children}
}
