// Code generated by htmlgen; DO NOT EDIT.
package html

type TypeRangeProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func TypeRange(p TypeRangeProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "type_range", props: a, void: false, children: children}
}
