// Code generated by htmlgen; DO NOT EDIT.
package html

type TypeRadioProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func TypeRadio(p TypeRadioProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "type_radio", props: a, void: false, children: children}
}
