// Code generated by htmlgen; DO NOT EDIT.
package html

type TypeDateProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func TypeDate(p TypeDateProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "type_date", props: a, void: false, children: children}
}
