// Code generated by htmlgen; DO NOT EDIT.
package html

type TypeButtonProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func TypeButton(p TypeButtonProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "type_button", props: a, void: false, children: children}
}
