// Code generated by htmlgen; DO NOT EDIT.
package html

type UProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func U(p UProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "u", props: a, void: false, children: children}
}
