// Code generated by htmlgen; DO NOT EDIT.
package html

type UnfencedTopProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func UnfencedTop(p UnfencedTopProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "unfencedTop", props: a, void: false, children: children}
}
