// Code generated by htmlgen; DO NOT EDIT.
package html

type UnsafeUrlProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func UnsafeUrl(p UnsafeUrlProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "unsafe-url", props: a, void: false, children: children}
}
