// Code generated by htmlgen; DO NOT EDIT.
package html

type UsbProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Usb(p UsbProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "usb", props: a, void: false, children: children}
}
