// Code generated by htmlgen; DO NOT EDIT.
package html

type UsemapProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Usemap(p UsemapProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "usemap", props: a, void: false, children: children}
}
