// Code generated by htmlgen; DO NOT EDIT.
package html

type UserScalableProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func UserScalable(p UserScalableProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "user-scalable", props: a, void: false, children: children}
}
