// Code generated by htmlgen; DO NOT EDIT.
package html

type ValignProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Valign(p ValignProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "valign", props: a, void: false, children: children}
}
