// Code generated by htmlgen; DO NOT EDIT.
package html

type ValueProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Value(p ValueProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "value", props: a, void: false, children: children}
}
