// Code generated by htmlgen; DO NOT EDIT.
package html

type VarProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Var(p VarProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "var", props: a, void: false, children: children}
}
