// Code generated by htmlgen; DO NOT EDIT.
package html

type VersionProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Version(p VersionProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "version", props: a, void: false, children: children}
}
