// Code generated by htmlgen; DO NOT EDIT.
package html

type VideoProps struct {
	ID, Class, Style, Title *string
	Attributes              []Attribute
}

func Video(p VideoProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "video", props: a, void: false, children: children}
}
