// Code generated by htmlgen; DO NOT EDIT.
package html

type ViewportFitProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func ViewportFit(p ViewportFitProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "viewport-fit", props: a, void: false, children: children}
}
