// Code generated by htmlgen; DO NOT EDIT.
package html

type ViewportProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Viewport(p ViewportProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "viewport", props: a, void: false, children: children}
}
