// Code generated by htmlgen; DO NOT EDIT.
package html

type VspaceProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Vspace(p VspaceProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "vspace", props: a, void: false, children: children}
}
