// Code generated by htmlgen; DO NOT EDIT.
package html

type WatchProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Watch(p WatchProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "watch", props: a, void: false, children: children}
}
