// Code generated by htmlgen; DO NOT EDIT.
package html

type WbrProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Wbr(p WbrProps) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "wbr", props: a, void: true}
}
