// Code generated by htmlgen; DO NOT EDIT.
package html

type WebShareProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func WebShare(p WebShareProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "web-share", props: a, void: false, children: children}
}
