// Code generated by htmlgen; DO NOT EDIT.
package html

type WebauthnProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Webauthn(p WebauthnProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "webauthn", props: a, void: false, children: children}
}
