// Code generated by htmlgen; DO NOT EDIT.
package html

type WebkitdirectoryProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Webkitdirectory(p WebkitdirectoryProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "webkitdirectory", props: a, void: false, children: children}
}
