// Code generated by htmlgen; DO NOT EDIT.
package html

type WhereProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Where(p WhereProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "where", props: a, void: false, children: children}
}
