// Code generated by htmlgen; DO NOT EDIT.
package html

type WidthProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Width(p WidthProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "width", props: a, void: false, children: children}
}
