// Code generated by htmlgen; DO NOT EDIT.
package html

type WildcardsProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Wildcards(p WildcardsProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "wildcards", props: a, void: false, children: children}
}
