// Code generated by htmlgen; DO NOT EDIT.
package html

type WindowManagementProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func WindowManagement(p WindowManagementProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "window-management", props: a, void: false, children: children}
}
