// Code generated by htmlgen; DO NOT EDIT.
package html

type WrapProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Wrap(p WrapProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "wrap", props: a, void: false, children: children}
}
