// Code generated by htmlgen; DO NOT EDIT.
package html

type XmlnsProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Xmlns(p XmlnsProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "xmlns", props: a, void: false, children: children}
}
