// Code generated by htmlgen; DO NOT EDIT.
package html

type XmpProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func Xmp(p XmpProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "xmp", props: a, void: false, children: children}
}
