// Code generated by htmlgen; DO NOT EDIT.
package html

type XrSpatialTrackingProps struct {
	ID, Class, Style, Title *string
	Attributes []Attribute
}

func XrSpatialTracking(p XrSpatialTrackingProps, children ...Node) Node {
	a := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)
	return elementNode{name: "xr-spatial-tracking", props: a, void: false, children: children}
}
