package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

type rec struct {
	Name string `json:"name"`
}

func main() {
	in := flag.String("input", "", "json root")
	out := flag.String("output", ".", "output")
	flag.Parse()
	if *in == "" {
		fmt.Fprintln(os.Stderr, "--input required")
		os.Exit(2)
	}
	root := filepath.Join(*in, "html", "elements")
	_ = filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() || filepath.Base(path) != "index.json" {
			return err
		}
		rel, _ := filepath.Rel(root, filepath.Dir(path))
		if strings.Contains(string(filepath.Separator)+rel+string(filepath.Separator), string(filepath.Separator)+"attributes"+string(filepath.Separator)) {
			return nil
		}
		var r rec
		b, _ := os.ReadFile(path)
		if json.Unmarshal(b, &r) != nil || r.Name == "" {
			return nil
		}
		if err := write(*out, r.Name); err != nil {
			panic(err)
		}
		return nil
	})
}
func write(dir, tag string) error {
	fn := filepath.Join(dir, kebab(tag)+".go")
	name := exported(tag)
	void := map[string]bool{"area": true, "base": true, "br": true, "col": true, "embed": true, "hr": true, "img": true, "input": true, "link": true, "meta": true, "param": true, "source": true, "track": true, "wbr": true}[tag]
	sig := fmt.Sprintf("func %s(p %sProps", name, name)
	if !void {
		sig += ", children ...Node"
	}
	sig += ") Node"
	body := fmt.Sprintf("// Code generated by htmlgen; DO NOT EDIT.\npackage html\n\ntype %sProps struct {\n\tID, Class, Style, Title *string\n\tAttributes []Attribute\n}\n\n%s {\n\ta := globalAttrs(p.ID, p.Class, p.Style, p.Title, p.Attributes)\n\treturn elementNode{name: %q, props: a, void: %t%s}\n}\n", name, sig, tag, void, func() string {
		if void {
			return ""
		}
		return ", children: children"
	}())
	return os.WriteFile(fn, []byte(body), 0644)
}
func exported(s string) string {
	var b strings.Builder
	up := true
	for _, r := range s {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			up = true
			continue
		}
		if up {
			b.WriteRune(unicode.ToUpper(r))
			up = false
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}
func kebab(s string) string { return strings.ToLower(s) }
